# eureka default port = 8761
server:
  port: 8761

# identify name in MSA
spring:
  application:
    name: eureka-server

# make client setting false
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false

# AP 로그 설정
logging:

  charset:
    console: UTF-8
    file: UTF-8

  file:
    name: ./log/${spring.application.name}.log
    max-history: 30

jasypt:
  encryptor:
    bean:
    password: 
